OTS/urls.py
from django.urls import path
from OTS.views import *
app_name = 'OTS'
urlpatterns = [
    path('',welcome),
    path('new-candidate',candidateRegistrationForm,name='registraionForm'),
    path('store-candidate',candidateRegistration,name='storeCandidate'),
    path('login',loginView,name='login'),
    path('home',candidateHome,name='home'),
    path('test-paper',testPaper,name='testPaper'),
    path('calculate-result',calculateTestResult,name='calculateTest'),
    path('test-history',testResultHistory,name='testHistory'),
    path('result',showtestResult,name='result'),
    path('logout',logoutView,name='logout'),
]

SolveIQ/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('OTS/',include('OTS.urls')),
]

OTS/models.py
from django.db import models

class Candidate(models.Model):
    username = models.CharField(primary_key=True, max_length=20)
    password = models.CharField(null=False, max_length=20)
    name = models.CharField(null=False, max_length=30)
    test_attempted = models.IntegerField(default=0)
    points = models.FloatField(default=0.0)
    def __str__(self):
        return self.username
class Question(models.Model):
    qid = models.BigAutoField(primary_key=True,auto_created=True)
    que = models.TextField()
    a = models.CharField(max_length=255)
    b = models.CharField(max_length=255)
    c = models.CharField(max_length=255)
    d = models.CharField(max_length=255)
    ans = models.CharField(max_length=2)
    def __str__(self):
        return self.que
class Result(models.Model):
    resultid = models.BigAutoField(primary_key=True, auto_created=True)
    username = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    date = models.DateField(auto_now=True)
    time = models.TimeField(auto_now=True)
    attempt = models.IntegerField()
    right = models.IntegerField()
    wrong = models.IntegerField()
    points = models.FloatField()
    # def __str__(self):
    #     return self.resultid

OTS/views.py
from django.shortcuts import render
from django.http import *
from OTS.models import *
import random

def welcome(request):
    return render(request,'welcome.html')

def candidateRegistrationForm(request):
    res = render(request,'registration_form.html')
    return res

def candidateRegistration(request):
    if request.method=='POST':
        username = request.POST['username']
        #Check if the user alreday exits
        if len(Candidate.objects.filter(username=username)):
            userStatus=1
        else:
            candidate=Candidate()
            candidate.username=username
            candidate.password=request.POST['password']
            candidate.name=request.POST['name']
            candidate.save()
            userStatus=2
    else:
        userStatus=3 #Request method is not POST
    context={
        'userStatus':userStatus
    }
    return render(request, 'registration.html',context)
 
def loginView(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        candidate=Candidate.objects.filter(username=username,password=password)
        if len(candidate)==0:
            loginError="Invaild Username or Password"
            res=render(request,'login.html',{'loginError':loginError})
        else:
            #login Success
            request.session['username']=candidate[0].username #making a session variable , exits until user not logout, and we can use this any views
            request.session['name']=candidate[0].name
            res=HttpResponseRedirect("home")
    else:
        res=render(request,'login.html')
    return res

def candidateHome(request):
    #chack that user come this page with login
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
    else:
        res=render(request,'home.html')
    return res

def testPaper(request):
    #chack that user come this page with login
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
    
    #fetch question from database table
    n=int(request.GET['n'])
    question_pool=list(Question.objects.all())
    random.shuffle(question_pool) #all the data inside the list got scattered
    questions_list=question_pool[:n]
    context={'questions':questions_list}
    res=render(request,'test_paper.html',context)
    return res

def calculateTestResult(request):
    #chack that user come this page with login
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")

    total_attempt=0
    total_right=0
    total_wrong=0
    qid_list=[]
    for k in request.POST:
        if k.startswith('qno'):
            qid_list.append(int(request.POST[k]))
    for n in qid_list:
        question=Question.objects.get(qid=n)
        try:
            if question.ans==request.POST['q'+str(n)]:
                total_right+=1
            else:
                total_wrong+=1
            total_attempt+=1
        except:
            pass
    points=(total_right-total_wrong)/len(qid_list)*10
    #store result in Result Table
    result=Result()
    result.username=Candidate.objects.get(username=request.session['username'])
    result.attempt=total_attempt
    result.right=total_right
    result.wrong=total_wrong
    result.points=points
    result.save()
    
    #update Candidate Table
    candidate=Candidate.objects.get(username=request.session['username'])
    candidate.test_attempted=+1
    candidate.points=(candidate.points*(candidate.test_attempted-1)+points)/candidate.test_attempted
    candidate.save()
    res = HttpResponseRedirect("result")
    return res

def testResultHistory(request):
    #chack that user come this page with login
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")

    candidate=Candidate.objects.filter(username=request.session['username'])
    results=Result.objects.filter(username_id=candidate[0].username)
    context={'candidate':candidate[0],'results':results}
    res=render(request,'candidate_history.html',context)
    return res

def showtestResult(request):
    #chack that user come this page with login
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
    
    #fetch latest result form Result table
    result=Result.objects.filter(resultid=Result.objects.latest('resultid').resultid,username_id=request.session['username'])
    context={'result':result}
    res=render(request,'show_result.html',context)
    return res

def logoutView(request):
    #chack that user come this page with login
    if 'name' in request.session.keys():
        del request.session['username']
        del request.session['name']
    res=HttpResponseRedirect("login")
    return res

OTS/templates/candidate_history.html
{% extends "main.html" %}

{% block title%} OTS - Candidate Result History {%endblock title%}

{% block top%}
<a href="{% url 'OTS:home' %}" class="btn btn-outline-primary" role="button">Home</a>
<a href="{% url 'OTS:logout' %}" class="btn btn-outline-primary" role="button">Logout</a>
{% endblock top%}

{% block content %}
<h1>Your Report Card</h1>
<p>Hi <span class="special">{{candidate.name}}</span>, 
    you have attempted in total <span class="special">{{candidate.test_attempted}}</span> test and you have scored <span class="special">{{candidate.points}}</span> on the scale of 10</p>
<table class="table table-striped table-hover">
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attempt</th>
        <th>Right</th>
        <th>Wrong</th>
        <th>Points</th>
    </tr>
    {% for r in results %}
    <tr>
        <td>{{r.date}}</td>
        <td>{{r.time}}</td>
        <td>{{r.attempt}}</td>
        <td>{{r.right}}</td>
        <td>{{r.wrong}}</td>
        <td>{{r.points}}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

OTS/templates/home.html
{% extends "main.html" %}

{% block title%} SolveIQ - Candidate Home Page {%endblock title%}

{% block top%}
<a href="{% url 'OTS:home' %}" class="btn btn-outline-primary" role="button">Home</a>
<a href="{% url 'OTS:logout' %}" class="btn btn-outline-primary" role="button">Logout</a>
{% endblock top%}

{% block content %}
<section class="text-black text-center py-5">
  <div class="container">
    <h1>Welcome {{request.session.name}}, to your home page</h1>
    <div class="d-grid gap-2">
        <!-- here "?n=1" go one data through the get method, variable name=n and vaue=1 -->
        <a href="{% url 'OTS:testPaper' %}?n=1" class="btn btn-outline-primary" role="button">Test of 1 Question</a>
        <a href="{% url 'OTS:testPaper' %}?n=3" class="btn btn-outline-primary" role="button">Test of 3 Question</a>
        <a href="{% url 'OTS:testPaper' %}?n=5" class="btn btn-outline-primary" role="button">Test of 5 Question</a>
        <a href="{% url 'OTS:testPaper' %}?n=10" class="btn btn-outline-primary" role="button">Test of 10 Question</a>
        <a href="{% url 'OTS:testHistory' %}" class="btn btn-outline-success" role="button">Test History</a>
        
        
        <!-- <a href="{% url 'OTS:testPaper' %}?n=1">Test of 1 Question</a> -->
    </div>
  </div>
</section>
{% endblock %}

OTS/templates/login.html
{% extends "main.html" %}

{% block title%} OTS - Login Form {%endblock title%}

{% block top%}
<a href="{% url 'OTS:registraionForm' %}" class="btn btn-outline-primary" role="button">SignIn</a>
{% endblock top%}

{% block content %}
<div class="all-forms vstack gap-3">
    {% if loginError %}
        <div id="error">{{loginError}}</div>
    {% endif %}
    <form action="{% url 'OTS:login' %}" method="post">
        {% csrf_token %}
        <div class="form-floating mb-3 p-2">
            <input type="text" class="form-control" id="floatingInput" name="username" placeholder="username">
            <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating p-2">
            <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="password">
            <label for="floatingPassword">Password</label>
        </div>
        <div class="d-grid gap-2 p-2">
            <button class="btn btn-primary" type="reset">Clear</button>
            <button class="btn btn-primary" type="submit">Submit</button>
        </div>
    </form>
    New user <a href="{% url 'OTS:registraionForm' %}">Click Here</a>
</div>
{% endblock %}

OTS/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'theme.css' %}">
    <link rel="stylesheet" href="{% static 'formstyle.css' %}">
    <link rel="stylesheet" href="{% static 'buttonstyle.css' %}">
    <link rel="icon" type="image/png" href="{% static 'SolveIQ_Logo_webIcon.png' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body>
    <nav class="top navbar bg-body-tertiary ">
        <div class="container">
            <a class="navbar-brand" href="{% url 'OTS:home' %}">
            <img src="{% static 'SolveIQ_Logo_forAllpage.png' %}" alt="SolveIQ" width="180" height="36">
            </a>
            <div class="menu">
                {% block top %} {% endblock %}
            </div>
        </div>
    </nav>

    <div class="content">
        {% block content %} {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
</body>
</html>

OTS/templates/registration.html
{% extends "main.html" %}

{% block title%} OTS-Registration Status {%endblock title%}

{% block top%}
<a href="{% url 'OTS:registraionForm' %}">Signup</a>
<a href="{% url 'OTS:login' %}">Login</a>
{% endblock top%}

{% block content %}
{% if userStatus == 1 %}
    <div class="userstatus">
        Sorry, username Already exits, Please try different username.
        <a href="{% url 'OTS:registraionForm' %}">Back to Candidte Registration Page</a>
    </div>
{% elif userStatus == 2 %}
    <div class="userstatus">
        Congratulations!! , User created successfully
        <a href="{% url 'OTS:login' %}">Login</a>
    </div>
{% elif userStatus == 3 %}
    <div class="userstatus">
        Oops!!, Improper Request
        <a href="{% url 'OTS:registrationForm' %}">Back to Candidate Registration Page</a>
    </div>
{% endif %}
{% endblock %}

OTS/templates/registration_form.html
{% extends 'main.html' %}

{% block title%} OTS-Registration Form {%endblock title%}

{% block top%}
<a href="{% url 'OTS:login' %}" class="btn btn-outline-primary" role="button">Login</a>
{% endblock top%}

{% block content %}
<div class="all-forms vstack gap-3">
    <form action="{% url 'OTS:storeCandidate' %}" method="post">
        {% csrf_token %}
        <div class="form-floating mb-3 p-2">
            <input type="text" class="form-control" id="floatingInput" name="username" placeholder="username">
            <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating p-2">
            <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="password">
            <label for="floatingPassword">Password</label>
        </div>
        <div class="form-floating mb-3 p-2">
            <input type="text" class="form-control" id="floatingInput" name="name" placeholder="name">
            <label for="floatingInput">Name</label>
        </div>
        <div class="d-grid gap-2 p-2">
            <button class="btn btn-primary" type="reset">Clear</button>
            <button class="btn btn-primary" type="submit">Submit</button>
        </div>

    </form>
    Already have an account, <a href="{% url 'OTS:login' %}">Click Here</a>
</div>
{% endblock %}

OTS/templates/show_result.html
{% extends "main.html" %}

{% block title%} OTS - Test Result {%endblock title%}

{% block top%}
<a href="{% url 'OTS:home' %}">Home</a>
<a href="{% url 'OTS:logout' %}">Logout</a>
{% endblock top%}

{% block content %}
    <table class="table table-striped table-hover">
        <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Attempt</th>
            <th>Right</th>
            <th>Wrong</th>
            <th>Points</th>
        </tr>
        {% for r in result %}
        <tr>
            <td>{{r.date}}</td>
            <td>{{r.time}}</td>
            <td>{{r.attempt}}</td>
            <td>{{r.right}}</td>
            <td>{{r.wrong}}</td>
            <td>{{r.points}}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

OTS/templates/test_paper.html
{% extends "main.html" %}

{% block title%} OTS - Test Paper {%endblock title%}

{% block top%}
{% endblock top%}

{% block content %}
<form action="{% url 'OTS:calculateTest' %}" method="post">
    {% csrf_token %}
    {% for question in questions %}
        <div class="question">
            <input type="hidden" name="qno{{question.qid}}" value="{{question.qid}}">
            {{question.que}}
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" id="radioDefault1" name="q{{question.qid}}" value="a">
            <label class="form-check-lable" for="radioDefault1">{{question.a}}</label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" id="radioDefault2" name="q{{question.qid}}" value="b">
            <label class="form-check-lable" for="radioDefault2">{{question.b}}</label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" id="radioDefault3" name="q{{question.qid}}" value="c">
            <label class="form-check-lable" for="radioDefault3">{{question.c}}</label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" id="radioDefault4" name="q{{question.qid}}" value="d">
            <label class="form-check-lable" for="radioDefault4">{{question.d}}</label>
        </div>
        
        <!-- <div class="options"><input type="radio" name="q{{question.qid}}" value="b">{{question.b}}</div>
        <div class="options"><input type="radio" name="q{{question.qid}}" value="c">{{question.c}}</div>
        <div class="options"><input type="radio" name="q{{question.qid}}" value="d">{{question.d}}</div> -->
    {% endfor %}

    <div class="d-grid gap-2"><button class="btn btn-primary" type="submit">Submit</button></div>
</form>
{% endblock %}

OTS/templates/welcome.html
{% extends "main.html" %}

{% block title%} SolveIQ {%endblock title%}

{% block top%}
<a href="{% url 'OTS:registraionForm' %}" class="btn btn-outline-primary" role="button">Signup</a>
<a href="{% url 'OTS:login' %}" class="btn btn-outline-primary" role="button">Login</a>
{% endblock top%}

{% block content %}
<section class="text-black text-center py-5">
  <div class="container">
    <h1>Welcome to Online Testing System</h1>
    <div class="d-grid gap-2">
        <!-- here "?n=1" go one data through the get method, variable name=n and vaue=1 -->
        <a href="{% url 'OTS:login' %}?n=1" class="btn btn-outline-primary" role="button">Test of 1 Question</a>
        <a href="{% url 'OTS:login' %}?n=3" class="btn btn-outline-primary" role="button">Test of 3 Question</a>
        <a href="{% url 'OTS:login' %}?n=5" class="btn btn-outline-primary" role="button">Test of 5 Question</a>
        <a href="{% url 'OTS:login' %}?n=10" class="btn btn-outline-primary" role="button">Test of 10 Question</a>
        <a href="{% url 'OTS:login' %}" class="btn btn-outline-success" role="button">Test History</a>
        
        
        <!-- <a href="{% url 'OTS:testPaper' %}?n=1">Test of 1 Question</a> -->
    </div>
  </div>
</section>
{% endblock %}